### ISSUE TITLE
Unexpected negative array access.

### ISSUE THREAD

**Issue by rdebath** [matslina/awib#1]
This BF generates

    +[>]<- [<<<<<<<<<<<<<<<<+>>>>>>>>>>>>>>>>-]

The below C code, notice the negative array index is accessed despite the fact that the second loop isn't run. The program mandelbrot.b has this sort of construct.
However, this doesn't actually segfault for me, but the @lang_go variant does throw the error both for my tiny example above and mandelbrot.b.

    #include <stdio.h>
    char    buf[0xffff];
    int
    main()
    {
        char   *p = buf;
        int     c;
        *p += 1;
        while (*p) {
            p += 1;
        }
        p -= 1;
        *p -= 1;
        *(p - 16) += *p * 1;
        *p = 0;
        return 0;
    }

**Comment by matslina** [comment]
Excellent catch!

As I'm sure you already know, this stems from the second loop being optimized as a multiplication loop. I'll have to put some more thought into it, but right now I can't think of anything better than either wrapping all such operations in if statements (i.e. `if (*p!=0)`)  or throwing the optimization out completely. If you have a better suggestion then I'm all ears!

And sorry for the 19 month delay in responding. I can't recall having noticed this issue until now, but it's also possible I was just too fed up with brainfuck at the time to look closer. Either way: thanks.

**Comment by rdebath** [comment]
The only "solution" I've seen is to shift the entire array by a few cells so you have some space "to the left" of zero. 

After that you know
1. That references less than `N` cells to the left of zero are safe.
2. That the cell referenced by the `[` must also be safe.

So you can deduce that any references less than `N` cells to the left of the most recent `[` are safe but any more than that you need to add the `if()`. This can also (sometimes) be extended to preceding or enclosing loops.

Of course, after coding that in brainfuck I wouldn't be surprised if you need another year or two to recover :smile:

**Comment by matslina** [comment]
That's definitely an option. 127 cells of padding should suffice, since that's the maximum offset awib will emit for this optimization. I'll have to take a closer look though. Could be that adding this to the 386 Linux backend is non-trivial.

**Comment by matslina** [comment]
I believe edae31cffc007a fixes this issue. Thanks again for reporting.
