### ISSUE TITLE
awib_make_binary.bin returns 141, fails make

### ISSUE THREAD

**Issue by zatherz** [matslina/awib#2]
Because of the lack of a return() statement in the main() function, awib_make_binary.bin returns with 141, which makes GNU make exit because of failure. Adding "return(0);" to the main() function in the C part of awib.b fixes that, but this thing is so messy that I have no idea where to even start fixing it.

**Comment by matslina** [comment]
That's a bummer. I realize you may not remember, it being 19 months later and all, but what version of gcc were you using? Platform? I get C99-like behaviour on gcc-4.8.4, i.e. 0 is returned.

I'm leaning towards just adding `-std=c99` to the Makefile, to keep the C part of awib.b as obfuscated as possible. Let me know if you have a strong preference though.

**Comment by zatherz** [comment]
Haha, I had to actually check what this whole project is about again after this time. If I remember correctly I was using clang, but even if I was using gcc it was on Arch Linux.
Thanks for the fix, I guess it helps. I don't care if it's written in a specific standard, as long as I don't have to touch it :).
